# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# GPG
export GPG_TTY=$(tty)

source ~/.zsh_plugins/zsh-snap/znap.zsh

znap source romkatv/powerlevel10k

# Plugins
znap source ohmyzsh/ohmyzsh
znap source ohmyzsh/ohmyzsh \
	plugins/{macos,colored-man-pages,gpg-agent} \
	plugins/{git,gitfast,git-extras} \
	plugins/{python,pip} \
	plugins/{node,npm,yarn} \
	plugins/{ruby,gem} \
	plugins/golang \
	plugins/{ansible,aws,kubectl,terraform,docker} \
	plugins/jira

znap source aloxaf/fzf-tab
# fnm is initialised in ~/.zsh/01-environment.zsh instead. Sourcing this as well
# ran `fnm env` twice per shell, and every run mints its own directory under
# ~/.local/state/fnm_multishells and prepends it to $PATH. The two runs also
# disagreed: the plugin resolved the default alias while the explicit eval
# resolved the version file, so which node you got came down to $PATH order.
# znap source dominik-schwabe/zsh-fnm
znap source djui/alias-tips
znap source marlonrichert/zsh-hist
znap source z-shell/F-Sy-H
znap eval zoxide "zoxide init --cmd j zsh"
znap source jeffreytse/zsh-vi-mode
# Point the plugin at the stowed config under XDG_CONFIG_HOME. It has no XDG
# support itself: unset, it reads ~/.fzf.zsh, and set, it reads
# $FZF_PATH/fzf.zsh, so this is the only lever available.
#
# Setting it also fixes a second problem. The plugin assigns FZF_PATH without
# declaring it local, and .zshrc sources the plugin twice, once here and once
# from zvm_after_init_commands so the key bindings survive zsh-vi-mode. Left
# unset, the first pass read ~/.fzf.zsh while the second saw the leaked value
# and read somewhere else entirely. Now both passes take the same branch.
#
# Caveat: FZF_PATH doubles as the plugin's clone target when fzf is missing, so
# a machine without it would get a git clone into this directory. fzf comes from
# brew here, so that path never runs.
export FZF_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/fzf"
znap source unixorn/fzf-zsh-plugin
export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_UNDERLINE
# Don't install fzf as this plugin does
zvm_after_init_commands+=('znap source unixorn/fzf-zsh-plugin')
# Zsh-users
znap source zsh-users/zsh-completions
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
znap source zsh-users/zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
ZSH_AUTOSUGGEST_STRATEGY=(history)
znap source zsh-users/zsh-autosuggestions

# Speed up pasting w/ autosuggest
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

plugins=()

# Source custom zsh files
for config ($HOME/.zsh/*.zsh) source $config

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

path=($HOME/.yarn/bin(N-/) $HOME/.config/yarn/global/node_modules/.bin(N-/) $path)

# Graphite completions, generated by `gt completion`. Loaded only when gt is
# installed so a machine without it doesn't pay for the compdef.
if (( $+commands[gt] )); then
  _gt_yargs_completions() {
    local reply si=$IFS
    IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" gt --get-yargs-completions "${words[@]}"))
    IFS=$si
    _describe 'values' reply
  }
  compdef _gt_yargs_completions gt
fi

